# Generated by Django 4.1.5 on 2023-01-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XlsSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.IntegerField()),
                ('package', models.BooleanField(max_length=255)),
                ('date_subscribed', models.DateField()),
                ('expiry_date', models.DateField()),
                ('champ_name', models.CharField(max_length=255)),
                ('tech_support_comment', models.BooleanField()),
                ('connection_status', models.CharField(max_length=255)),
                ('package_status', models.BooleanField(max_length=255)),
                ('building_name', models.CharField(max_length=255)),
            ],
        ),
    ]
