# Generated by Django 4.1.5 on 2023-01-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XlsSheet',
            new_name='ConnectedTVs',
        ),
    ]
