# Generated by Django 4.1.5 on 2023-01-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0002_rename_xlssheet_connectedtvs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectedtvs',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='connectedtvs',
            name='package',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connectedtvs',
            name='package_status',
            field=models.CharField(max_length=255),
        ),
    ]
