# Generated by Django 4.1.5 on 2023-01-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0005_alter_connectedtvs_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedtvs',
            name='tv_mac',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
