# Generated by Django 4.1.5 on 2023-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0006_connectedtvs_tv_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='tech_support_comment',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
