# Generated by Django 4.1.5 on 2023-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0007_alter_connectedtvs_tech_support_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
