# Generated by Django 4.1.5 on 2023-01-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0008_alter_connectedtvs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='date_subscribed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='connectedtvs',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='connectedtvs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='connectedtvs',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
