# Generated by Django 4.1.5 on 2023-01-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0009_alter_connectedtvs_date_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
