# Generated by Django 4.1.5 on 2023-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0011_alter_connectedtvs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
