# Generated by Django 4.1.5 on 2023-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0012_alter_connectedtvs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtvs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
