# Generated by Django 4.1.5 on 2023-01-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnect_admin', '0013_alter_connectedtvs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedtvs',
            name='tech_support_comment',
        ),
    ]
